### ISSUE TITLE
RDL_123 has no traitDeCote.geojson

### ISSUE THREAD

**Issue by grassick** [Ouranosinc/panacees-web#4]

**Comment by grassick** [comment]
@Zeitsperre This is still an issue. Opening RDL_123 does not work

**Comment by Zeitsperre** [comment]
Would it be possible to remove this cell? I had to poke around and it seems that this cell is a residual/error.

![image](https://user-images.githubusercontent.com/10819524/102090633-b187ad80-3deb-11eb-86fe-415da20f1fa4.png)

I'll keep poking around to make sure but if that's all it is. We might want to sanitize it from the interface and CSVs in our data set.

**Comment by Zeitsperre** [comment]
Looks to be the case for all of these residuals. 

![image](https://user-images.githubusercontent.com/10819524/102091353-b731c300-3dec-11eb-98ba-e7cd8cd1dfaf.png)

Perhaps C-A and I can look into ways of removing these cells from everything, seeing as they aren't relevant to any analysis. I wouldn't do this before the workshop.
