### ISSUE TITLE
Page navigation disappears at width < 500 px

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/panacees-web#7]
When splitting the window across a monitor, the page titles (ie: navigation) disappears when width is below ~500 px. 

Some examples best illustrate this. Normal view:
![image](https://user-images.githubusercontent.com/10819524/95237325-0bf60380-07d6-11eb-879e-cebf7554c22c.png)

Constrained to ~500 px:
![image](https://user-images.githubusercontent.com/10819524/95237493-4b245480-07d6-11eb-9945-fd976b6a0fdd.png)

**Comment by grassick** [comment]
Fixed to collapse properly on narrow widths
