### ISSUE TITLE
Space out the page titles

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/panacees-web#8]
I'm currently adding a few more changes to the Markdown, but this change falls into CSS. Project lead wants the page titles to be a bit more spaced out. Given that this page is reactive to window/screen size, there must be a way to maybe make the spacing of page titles bi-modal (follow percentages for larger screens, minimum distance for smaller screens?).

For reference:
![image](https://user-images.githubusercontent.com/10819524/95237871-bc640780-07d6-11eb-8120-8e4cee5a2e57.png)

**Comment by grassick** [comment]
This and #7 should probably wait until we've settled on a Bootstrap theme. Then I can make the required adjustments. I'm ready whenever Chantal is to work through that part of the project.
